### ISSUE TITLE
[help] Scan unique ids only

### ISSUE THREAD

**Issue by duceduc** [OpenWonderLabs/node-switchbot#11]
Hello.  The below code will scan and display any devices it finds within xx seconds. This will include duplicates. How to display only unique ids'. Thank you.

    // Load the node-switchbot and get a `Switchbot` constructor object
    const Switchbot = require('node-switchbot');
    // Create an `Switchbot` object
    let switchbot = new Switchbot();

    // Start to monitor advertisement packets
    switchbot.startScan().then(() => {
      // Set an event hander
      switchbot.onadvertisement = (ad) => {
        console.log(JSON.stringify(ad, null, '  '));
      };
      // Wait 10 seconds
      return switchbot.wait(10000);
    }).then(() => {
      // Stop to monitor
      switchbot.stopScan();
      process.exit();
    });

**Comment by dnicolson** [comment]
I'm not sure it would make sense for this to be part of the module. You can achieve the desired functionality quite easily:

```
const Switchbot = require('node-switchbot');
const switchbot = new Switchbot();
const foundAddresses = [];

switchbot.startScan().then(() => {
  switchbot.onadvertisement = ad => {
    if (foundAddresses.indexOf(ad.address) === -1) {
      console.log(ad);
      foundAddresses.push(ad.address);
    }
  };
  return switchbot.wait(10000);
}).then(() => {
  switchbot.stopScan();
  process.exit();
});
```

**Comment by futomi** [comment]
@duceduc, `startScan()` method reports all advertising packets. The purpose of this method is monitoring status of device.

**Comment by duceduc** [comment]
Thanks for the write-up. I am not sure how to go about it, but I want to get details for all the devices I have by creating a rest sensor (Home Assistant) from this json list. So far, I have save it to a file and able to view it via locally on web. Can the code be further tweak to sort it in a fix order? Perhaps by address?

**Comment by futomi** [comment]
> Perhaps by address?

Yes, you should use the value of the `address`. The value of the `address` is a MAC address which is globally unique.

**Comment by duceduc** [comment]
If you guys have any pointers as to how to sort the unique list, that would be awesome. my js knowledge is very limited. Thanks.
