### ISSUE TITLE
Curtain Bot: No movement

### ISSUE THREAD

**Issue by duceduc** [OpenWonderLabs/node-switchbot#12]
Has anyone got the curtain device to work? I've received me a few days ago and tying to get the device to move, but with no luck. This is the code I am using and the error I am receiving.

    const Switchbot = require('node-switchbot');
    // Create an `Switchbot` object
    let switchbot = new Switchbot();

    switchbot.discover({ model: 'c', quick: true }).then((device_list) => {
      return device_list[0].close();
    }).then(() => {
      console.log('Done.');
    }).catch((error) => {
      console.error(error);
    });

Error:

    Error: No service was found.
    at /home/pi/node_modules/node-switchbot/lib/switchbot-device.js:228:18
    at Peripheral.<anonymous> (/home/pi/node_modules/@abandonware/noble/lib/peripheral.js:81:7)
    at Object.onceWrapper (node:events:436:26)
    at Peripheral.emit (node:events:329:20)
    at Noble.onServicesDiscover (/home/pi/node_modules/@abandonware/noble/lib/noble.js:309:16)
    at NobleBindings.emit (node:events:329:20)
    at NobleBindings.onServicesDiscovered (/home/pi/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:317:8)
    at Gatt.emit (node:events:329:20)
    at Object.callback (/home/pi/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:369:12)
    at Gatt.onAclStreamData (/home/pi/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:133:26)

**Comment by dnicolson** [comment]
I am also experiencing the same problem, although only on Linux and not macOS.

It appears that the SwitchBot Curtain exposes two BLE interfaces and when running on Linux it is picking up the wrong one.

Here is the advertisement data for the peripheral on macOS:
```
  advertisement: {
    localName: 'WoCurtain',
    manufacturerData: <Buffer 59 00 fc 71 xx xx xx xx>,
    serviceData: [ { uuid: '0d00', data: <Buffer 63 d0 4e 64 12> } ],
    serviceUuids: [ 'cba20d00224d11e69fb80002a5d5c51b' ]
  }
```

And on Linux:
```
  advertisement: {
    localName: undefined,
    txPowerLevel: undefined,
    manufacturerData: <Buffer 59 00 fc 71 xx xx xx xx>,
    serviceData: [ { uuid: '0d00', data: <Buffer 63 d0 4e 62 12> } ],
    serviceUuids: [ 'cba20d00224d11e69fb80002a5d5c51b' ],
    solicitationServiceUuids: [],
    serviceSolicitationUuids: []
  }
```

The manufacturer data above for equals that of the `A4C0DD7D-...` UUID on both macOS and Linux, the peripheral data on macOS also includes this UUID. On Linux though, the `_noble.address` value is a MAC address that corresponds with the `D00722CF-...` UUID.

This BlueSee table below appears to show additional BLE devices for each SwitchBot Curtain.

<img width="764" alt="Screen Shot 2020-11-28 at 19 24 23" src="https://user-images.githubusercontent.com/2276355/100523252-60eb4000-31af-11eb-8e6f-7ce8074242a3.png">

**Comment by dnicolson** [comment]
@SwitchBot-Wonderlabs does any of this make sense?

**Comment by duceduc** [comment]
Hope to get it sorted on Linux.

**Comment by duceduc** [comment]
No leads as to what is causing the issue?

**Comment by cholawo** [comment]
If it's any help to you, I finally got curtains working on my rpi (4b).   I did see there were big differences in the returned data between os x and the rpi.  Eventually I found that just constantly retrying the command on pi got it to eventually work.  I expect it's some kind of pi bluetooth issue with noble not being ready or being busy.   Also I had all kinds of faff with a USB 3 hard drive killing bluetooth so if you have one I suggest moving it to a USB 2 port and testing again.

I ended up with this kind of thing (code simplified as I'm actually using a node-red node).

```const Switchbot = require('node-switchbot');
const noble = require('@abandonware/noble');
const switchbot = new Switchbot({'noble': noble});
let attempt = 0;

const doAction = async (command, device) => {
    if (attempt > 50) {
        console.log('quitting because 50 attempts');
        return;
    }
    try {
        await device[command]();
        console.log('success at attempt ', attempt);
        return;
    } catch (error) {
        console.log('failed at attempt ', attempt);
        attempt++;
        return doAction(command, device);
    }
};

const bot_list = await switchbot.discover({ quick: true });
doAction('open', bot_list[0]);

**Comment by cholawo** [comment]
@duceduc by the way, I believe that _noble.address is the mac of my rpi bluetooth.   So I don't believe that there really are two curtain ble devices per curtain.
```SwitchbotDeviceWoCurtain {
  _peripheral: Peripheral {
    _noble: Noble {
      initialized: true,
      address: 'dc:a6:32:0d:0e:87',
      _state: 'poweredOn',
      _bindings: [NobleBindings],
      _peripherals: [Object],
      _services: [Object],
      _characteristics: [Object],
      _descriptors: [Object],
      _discoveredPeripheralUUids: [Array],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _allowDuplicates: false
    },
    id: 'e79d56774c77',
    uuid: 'e79d56774c77',
    address: 'e7:9d:56:77:4c:77',
    addressType: 'random',
    connectable: true,
    advertisement: {
      localName: undefined,
      txPowerLevel: undefined,
      manufacturerData: <Buffer 59 00 e7 9d 56 77 4c 77>,
      serviceData: [Array],
      serviceUuids: [Array],
      solicitationServiceUuids: [],
      serviceSolicitationUuids: []
    },
    rssi: -70,
    services: null,
    mtu: null,
    state: 'disconnected'
  },
  _chars: null,
  _SERV_UUID_PRIMARY: 'cba20d00224d11e69fb80002a5d5c51b',
  _CHAR_UUID_WRITE: 'cba20002224d11e69fb80002a5d5c51b',
  _CHAR_UUID_NOTIFY: 'cba20003224d11e69fb80002a5d5c51b',
  _CHAR_UUID_DEVICE: '2a00',
  _READ_TIMEOUT_MSEC: 3000,
  _WRITE_TIMEOUT_MSEC: 3000,
  _COMMAND_TIMEOUT_MSEC: 3000,
  _id: 'e79d56774c77',
  _address: 'e7:9d:56:77:4c:77',
  _model: 'c',
  _modelName: 'WoCurtain',
  _was_connected_explicitly: false,
  _connected: false,
  _onconnect: [Function],
  _ondisconnect: [Function],
  _ondisconnect_internal: [Function],
  _onnotify_internal: [Function]
}
```
```pi@raspberrypi:~ $ hciconfig
hci0:	Type: Primary  Bus: UART
	BD Address: DC:A6:32:0D:0E:87  ACL MTU: 1021:8  SCO MTU: 64:1
	UP RUNNING 
	RX bytes:100946 acl:729 sco:0 events:4749 errors:0
	TX bytes:30980 acl:917 sco:0 commands:1430 errors:0
```

**Comment by duceduc** [comment]
Hi @cholawo,
It's working now. 

Your reply got me going back and fiddling with the code once again. Apparently, there is a conflict running more than one node app on the same server. I was running a node app for the switchbot bot. When I got the curtain bots, I figure I can just setup another node app but run it on a different port. It doesn't look like we can. When I stop the 1st node app, the curtain bot works.

**Comment by cholawo** [comment]
Happy to help.   I can't think why there should be a limit on the number of node apps you can run unless they are both trying to use your Bluetooth simultaneously to send commands to your bots at the same time.
