### ISSUE TITLE
[Request] Pause/Stop for Curtain

### ISSUE THREAD

**Issue by duceduc** [OpenWonderLabs/node-switchbot#16]
I noticed the app has a pause button to stop the curtain during movement. Is it possible to get this as well?

![File 2020-12-31 8 26 37 AM](https://user-images.githubusercontent.com/20457723/103386451-3ab81780-4b42-11eb-9c2a-0c843a8dc1ca.png)

**Comment by SwitchBot-Wonderlabs** [comment]
@duceduc I'll add it in a few days.

**Comment by duceduc** [comment]
Thank you for the adding the `pause` function. Working on my setup.
