### ISSUE TITLE
Option for device password

### ISSUE THREAD

**Issue by 1RandomDev** [OpenWonderLabs/node-switchbot#30]
**Is your feature request related to a problem? Please describe.**
Yes devics with a password can't be used with this API

**Describe the solution you'd like**
An option to define a device password when connecting to a SwitchBot

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lmEshoo** [comment]
@donavanbecker any timeline for this?

**Comment by donavanbecker** [comment]
@lmEshoo, wouldn't know how to implement this. If someone would push up a PR, I would merge it.
