### ISSUE TITLE
Bot ID Length

### ISSUE THREAD

**Issue by bevanjkay** [OpenWonderLabs/node-switchbot#38]
**Describe The Bug:**
The discover function allows passing an ID to find a specific bot, however this input is limited to 17 characters. 
The IDs on my switchbots are 32 character long `783deb2ef79841c28dc441c922ce36b0`

**To Reproduce:**

**Expected behavior:**

**Logs:**

**Comment by bevanjkay** [comment]
Bump

**Comment by donavanbecker** [comment]
[Line 263](https://github.com/OpenWonderLabs/node-switchbot/blob/latest/lib/switchbot.js)

The ID should be 17 as it is the same as the Mac Address. Should be able to close this.

**Comment by bevanjkay** [comment]
> [Line 263](https://github.com/OpenWonderLabs/node-switchbot/blob/latest/lib/switchbot.js)
> 
> The ID should be 17 as it is the same as the Mac Address. Should be able to close this.

That's definitely not the case when I was testing my setup. It required the device ID as provided when searching for the devices. 

I modified this package locally to increase the limit to 32 and passed the ID as returned by the GET request and it worked as expected.

**Comment by bevanjkay** [comment]
@donavanbecker This issue is still live, but I can't reopen.
