### ISSUE TITLE
[Request] Function to connect the device manually

### ISSUE THREAD

**Issue by sohsatoh** [OpenWonderLabs/node-switchbot#9]
Hi.
Maybe I'm just missing it on README, but is there a way to connect to a device with a MAC address?

**Comment by duceduc** [comment]
I am not sure if the bot device is what you want to connect too. The below code will 'Press' the bot when call 'http://ip:5002?id=mac'.

    const http = require('http');
    const url = require('url');
    const Switchbot = require('node-switchbot');

    const requestListener = function (req, res) {
     const queryObject = url.parse(req.url, true).query;
     res.writeHead(200);

     let device = null;

     if (queryObject == undefined || queryObject.id == undefined)
      return res.end('Please specify an id');

     const switchbot = new Switchbot();

     switchbot.discover({ id: queryObject.id, quick: true }).then((device_list) => {
      if (device_list == undefined || device_list.length == 0) {
       console.log('#device: notfound');
       res.end('no device');
      }
      device = device_list[0];

      console.log('#devicefound: ' + device.modelName + ' (' + device.address + ')');
      return true; //device.connect();
     }).then(() => {
      console.log('#device:press');
      return device.press();
     }).then(() => {
      console.log('#device:waiting');
      return switchbot.wait(1000);
     }).then(() => {
      console.log('#device:disconnecting');
      return device.disconnect();
     }).then(() => {
      console.log('Done.');
      res.end('OK!');
     }).catch((error) => {
      console.error(error);
      res.end('error: ' + error);
     });
    };

    const server = http.createServer(requestListener);
    server.timeout = 5 * 1000;
    server.listen(5002);

    console.log('#http:started');

**Comment by futomi** [comment]
Hi, @sohsatoh.

Unfortunately, there is no way to connect your device with the MAC address directly. It is due to the restriction of [noble](https://github.com/abandonware/noble) which is a BEL module.

Instead, this module supports ID (MAC address) filter. You can pass a ID (MAC address) to the [`startScan()`](https://github.com/futomi/node-switchbot#startscan-method) method. See the sample code for more details.

Thank you.

**Comment by sohsatoh** [comment]
Hi, sorry, I forgot to reply.
Thanks, I finally understand how it works:)
